project:
  type: default
  output-dir: _output
  render:
    - article.qmd
    - supplement.qmd
    - cover-letter.qmd

format:
  jmlr-pdf:
    keep-tex: true
    include-in-header: panel-layout.tex

execute:
  freeze: auto
  echo: false
  warning: false
  message: false
